name: Build Web

on: 
    push:
        branches:
            - lab7
    pull_request:
        branches:
            - lab7

jobs:
    build-windows-app:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: stable
                flutter-version: 3.22.2

            - name: Get dependancies
              run: flutter pub get

            - run: flutter build web --release lib/templates/lab7/main.dart